### ISSUE TITLE
Read up on Plotly Library. Visualize results from task 3. Show the top university by tuition fees, another viz showing top university by in state fees, then another showing for enrollment

### ISSUE THREAD

**Issue by TelRich** [TelRich/National-University-Ranking-App#18]

**Comment by Umanae** [comment]
# for top university by rank.
fig = px.bar(df_nur, y="rank", x="name", color="name", text_auto=True,height = 900, width= 2500)
fig.update_layout(barmode="stack", xaxis={"categoryorder": "total ascending"}, title_text="Top Universities by Ranking")
fig.show() 

# top university by tuition_and_fees
fig = px.bar(df_nur, y=["tuition_and_fees"], x="name", color="name", text_auto=True,height = 900, width= 2500)
fig.update_layout(barmode="stack", xaxis={"categoryorder": "total descending"}, title_text="Top Universities by tuition_and_fees")
fig.show()

# top university by undergrad_enrollment 
fig = px.bar(df_nur, y="undergrad_enrollment", x="name", color="name", text_auto=True,height = 900, width= 2500)
fig.update_layout(barmode="stack", xaxis={"categoryorder": "total descending"}, title_text="Top Universities by undergrad_enrollment")
fig.show()
